export const SAVING_CHART = "SAVING_CHART";
export const SAVE_CHART = "SAVE_CHART";
export const DELETE_CHART = "DELETE_CHART";
export const RECEIVE_CHARTS = "RECEIVE_CHARTS";
export const REQUEST_CHARTS = "REQUEST_CHARTS";
